// [snowpack] add styles to the page (skip if no document exists)
if (typeof document !== 'undefined') {
  const code = "/*\n * renexmoe v1.1.6 (https://github.com/186526/onemanager-theme-renexmoe)\n * Copyright 2020-2021 186526 <i@186526.xyz>\n * Licensed under GPL-3.0\n */\n@font-face {\n  font-family: \"Product Sans\";\n  src: local(\"Product Sans Regular\"), local(\"Google Sans Regular\"),\n    url(https://cdn.jsdelivr.net/gh/186526/jsdelivr@1.1.8/static/ProductSans-Regular.woff2)\n      format(\"woff2\");\n}\n\nbody {\n  font-family: Roboto, Noto Sans SC, Noto, Helvetica, Arial, sans-serif;\n}\n\n.mdui-container {\n  max-width: 950px;\n}\n\n.mdui-drawer-close {\n  display: none;\n}\n\n.mdui-drawer .mdui-list-item {\n  padding-left: 20px;\n  border-radius: 0 50px 50px 0;\n}\n\n.mdui-toolbar > a,\n.mdui-chip-title,\n.mdui-dialog-title {\n  font-family: Product Sans, Noto Sans SC, Roboto, Noto, Helvetica, Arial,\n    sans-serif;\n}\n\nfooter a {\n  text-decoration: none;\n}\n\n.mdui-chip {\n  margin: 20px;\n}\n\n.mdui-typo h1,\n.mdui-typo h2,\n.mdui-typo h3,\n.mdui-typo h4,\n.mdui-typo h5,\n.mdui-typo h6 {\n  font-family: Product Sans, Noto Sans SC;\n  margin-top: 0.2em;\n}\n\n@media (max-width: 740px) {\n  .mdui-col-sm-2,\n  .mdui-col-sm-3,\n  .forcedownload {\n    display: none;\n  }\n\n  .mdui-col-xs-12 {\n    width: 100%;\n  }\n}\n\n@media (max-width: 1024px) {\n  .mdui-drawer .mdui-list-item {\n    margin-right: 5px;\n  }\n}\n\n.mdui-list-item-icon {\n  --iconcolor: #656565;\n  color: var(--iconcolor) !important;\n}\n\n.mdui-theme-layout-dark .mdui-list-item-icon {\n  --iconcolor: #dadada !important;\n}\n\n.mdui-theme-layout-dark .mdui-list-item-active{\n  --color-active: rgb(255, 255, 255) !important;\n}\n\n.mdui-typo {\n  border-radius: 8px;\n}\n\n.mdui-dialog {\n  border-radius: 8px;\n}\n\n/* .mdui-container .mdui-list-item {\n  border-radius: 50px;\n} */\n\n#file {\n  margin-top: 1%;\n}\n\n#head-md,\n#readme-md {\n  display: none;\n}\n\n.mdui-theme-layout-dark .hljs-keyword,\n.hljs-selector-tag {\n  color: #dadada !important;\n}\n\nhtml *::-webkit-scrollbar {\n  width: 6px;\n  height: 4px;\n  border-radius: 4px;\n}\nhtml ::-webkit-scrollbar-thumb {\n  background: rgba(0, 0, 0, 0.3);\n}\n\n.mdui-dialog-actions .mdui-btn {\n  border-radius: 4px;\n}\n\n.mdui-menu {\n  border-radius: 6px;\n}\n";

  const styleEl = document.createElement("style");
  const codeEl = document.createTextNode(code);
  styleEl.type = 'text/css';
  styleEl.appendChild(codeEl);
  document.head.appendChild(styleEl);
}